- hosts: centos
  become: yes

  tasks:
    - name: install package
      yum:
        name: "{{ package_list }}"
      vars:
        package_list:
          - gcc
          - wget
          - git
          - vim
          - make
          - patch
          - libselinux-python
          - python-passlib
          - zsh
          - ncurses-devel

    - name: git clone
      git:
        repo: https://github.com/ryuichi1208/dotfiles.git
        dest: "~/dotfiles"

    - name: SELinux Disable
      selinux: state=disabled

    - name: Stop firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: reboot
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 60
