- hosts: all
  become: yes
  user: root
  tasks:

      - name: install via yum
        yum: name={{ item }} state=installed
        with_items:
            - vim
            - bash-completion
            - git
            - jq
            - tmux

      - name: SELinux
        selinux: state=disabled

      - name: reboot
        command: "/sbin/shutdown -r now"
 
      - name: wait for SSH port down
        wait_for:
          host: "{{ inventory_hostname }}"
          port: 22
          state: stopped
        delegate_to: 127.0.0.1
 
      - name: wait for SSH port up
        wait_for:
          host: "{{ inventory_hostname }}"
          port: 22
          state: started
          delay: 30
        delegate_to: 127.0.0.1
 
      - name: test connection (after reboot)
        ping

      - name: mount image folder share
        mount: fstype="cifs"
        opts="domain=MY_DOMAIN,username=USER,password=PASSWORD"
        src="//network_path/folder"
        name="/local_path/folder"        
